"use strict";
var gfg = ThisCouldBeBetter.GameFramework;
// Geometry.
var Camera = gfg.Camera;
var Coords = gfg.Coords;
var Direction = gfg.Direction;
var Disposition = gfg.Disposition;
var Orientation = gfg.Orientation;
var Polar = gfg.Polar;
var RangeExtent = gfg.RangeExtent;
var Rotation = gfg.Rotation;
// Geometry - Collisions.
var Collision = gfg.Collision;
var CollisionHelper = gfg.CollisionHelper;
var CollisionTrackerBase = gfg.CollisionTrackerBase;
var CollisionTrackerMapped = gfg.CollisionTrackerMapped;
var CollisionTrackerMappedMap = gfg.CollisionTrackerMappedMap;
var CollisionTrackerMappedMapCell = gfg.CollisionTrackerMappedMapCell;
// Geometry - Constraints.
var Constraint_AttachToEntityWithName = gfg.Constraint_AttachToEntityWithName;
var Constraint_Conditional = gfg.Constraint_Conditional;
var Constraint_ContainInBox = gfg.Constraint_ContainInBox;
var Constraint_ContainInHemispace = gfg.Constraint_ContainInHemispace;
var Constraint_FrictionDry = gfg.Constraint_FrictionDry;
var Constraint_FrictionXY = gfg.Constraint_FrictionXY;
var Constraint_Gravity = gfg.Constraint_Gravity;
var Constraint_SpeedMaxXY = gfg.Constraint_SpeedMaxXY;
var Constraint_TrimToPlaceSize = gfg.Constraint_TrimToPlaceSize;
var Constraint_WrapToPlaceSize = gfg.Constraint_WrapToPlaceSize;
var Constraint_WrapToPlaceSizeXTrimY = gfg.Constraint_WrapToPlaceSizeXTrimY;
// Geometry - Network.
var Network = gfg.Network;
// Geometry - Shapes.
var Arc = gfg.Arc;
var Box = gfg.Box;
var BoxRotated = gfg.BoxRotated;
var Cylinder = gfg.Cylinder;
var Edge = gfg.Edge;
var Face = gfg.Face;
var Hemispace = gfg.Hemispace;
var Path = gfg.Path;
var PathBuilder = gfg.PathBuilder;
var Plane = gfg.Plane;
var Point = gfg.Point;
var Ray = gfg.Ray;
var ShapeContainer = gfg.ShapeContainer;
var ShapeGroupAll = gfg.ShapeGroupAll;
var ShapeGroupAny = gfg.ShapeGroupAny;
var ShapeInverse = gfg.ShapeInverse;
var Shell = gfg.Shell;
var Sphere = gfg.Sphere;
var Wedge = gfg.Wedge;
var MapCellCollidable = gfg.MapCellCollidable;
var MapLocated = gfg.MapLocated;
var MapOfCells = gfg.MapOfCells;
var MapOfCellsCellSourceArray = gfg.MapOfCellsCellSourceArray;
// Geometry - Shapes - Meshes.
var Mesh = gfg.Mesh;
var MeshTextured = gfg.MeshTextured;
var Transform_Dynamic = gfg.Transform_Dynamic;
var Transform_Locate = gfg.Transform_Locate;
var Transform_Multiple = gfg.Transform_Multiple;
var Transform_Orient = gfg.Transform_Orient;
var Transform_Rotate2D = gfg.Transform_Rotate2D;
var Transform_RotateRight = gfg.Transform_RotateRight;
var Transform_Scale = gfg.Transform_Scale;
var Transform_Translate = gfg.Transform_Translate;
var Transforms = gfg.Transforms;
