"use strict";
// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord {
    static buildTime() { return new Date(2024, (parseInt("08") - 1), parseInt("03"), parseInt("10"), parseInt("21"), parseInt("11")); }
    static version() { return "unknown"; }
}
