"use strict";
// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord {
    static buildTime() { return new Date(2023, (parseInt("12") - 1), parseInt("11"), parseInt("22"), parseInt("30"), parseInt("38")); }
    static version() { return "v0.0.0-20231121-1624-25-g2b9a320"; }
}
