// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord 
{ 
static buildTime(): Date { return new Date(2024, (parseInt("09") - 1), parseInt("30"), parseInt("20"), parseInt("19"), parseInt("13")); } 
static version(): string { return "unknown"; } 
} 
