// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord 
{ 
static buildTime(): Date { return new Date(2024, (parseInt("09") - 1), parseInt("11"), parseInt(" 0"), parseInt("15"), parseInt("44")); } 
static version(): string { return "unknown"; } 
} 
