"use strict";
// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord {
    static buildTime() { return new Date(2024, (parseInt("09") - 1), parseInt("04"), parseInt("22"), parseInt("43"), parseInt("34")); }
    static version() { return "unknown"; }
}
