// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord 
{ 
static buildTime(): Date { return new Date(2023, (11 - 1), 27, 23, parseInt("22"), parseInt("09")); } 
static version(): string { return "v0.0.0-20231121-1624-11-gfb0878d"; } 
} 
