"use strict";
// Classes from the framework must be imported here
// or in some other _Imports.ts file
// so that they can be referenced without using the namespace.
// Generated by the _Build.bat or .sh scripts. 
// hack
// These classes currently have to come first.
var RandomizerLCG = gf.RandomizerLCG;
